/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alphatechsz.computerstore;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
/**
 *
 * @author Haqim
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        getContentPane().setBackground(new Color(164, 219, 232));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuLabel = new javax.swing.JLabel();
        toComputerMenuButton = new javax.swing.JToggleButton();
        toProfileButton = new javax.swing.JToggleButton();
        logoutButton = new javax.swing.JToggleButton();
        toSoftwareSystemMenuButton = new javax.swing.JButton();
        toIoDeviceMenu = new javax.swing.JButton();
        toOrderMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setIconImage(new ImageIcon("C:\\Users\\Haqim\\Documents\\Management and Science University\\OOP\\LAB REPORT (A3)\\ComputerStore\\src\\main\\java\\com\\alphatechsz\\computerstore\\AlphaTechszLogo.png").getImage());

        mainMenuLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        mainMenuLabel.setText("Main Menu");

        toComputerMenuButton.setText("Computer Menu");
        toComputerMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toComputerMenuButtonActionPerformed(evt);
            }
        });

        toProfileButton.setText("Profile");
        toProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toProfileButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        toSoftwareSystemMenuButton.setText("Software System Menu");
        toSoftwareSystemMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toSoftwareSystemMenuButtonActionPerformed(evt);
            }
        });

        toIoDeviceMenu.setText("IO Device Menu");
        toIoDeviceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toIoDeviceMenuActionPerformed(evt);
            }
        });

        toOrderMenuButton.setText("Order");
        toOrderMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toOrderMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toProfileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(toComputerMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toSoftwareSystemMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toIoDeviceMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toOrderMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toComputerMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toSoftwareSystemMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toIoDeviceMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toOrderMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toOrderMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toOrderMenuButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        OrderMenu orderMenu = new OrderMenu();
        orderMenu.setVisible(true);
    }//GEN-LAST:event_toOrderMenuButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
        JOptionPane.showMessageDialog(null, "Logout successfully",
            "Logout Message", JOptionPane.INFORMATION_MESSAGE);
        LoginMenu loginMenu = new LoginMenu();
        loginMenu.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void toSoftwareSystemMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toSoftwareSystemMenuButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        SoftwareSystemMenu softwareSystemMenu = new SoftwareSystemMenu();
        softwareSystemMenu.setVisible(true);
    }//GEN-LAST:event_toSoftwareSystemMenuButtonActionPerformed

    private void toComputerMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toComputerMenuButtonActionPerformed
        this.dispose();
        ComputerMenu computerMenu = new ComputerMenu();
        computerMenu.setVisible(true);
    }//GEN-LAST:event_toComputerMenuButtonActionPerformed

    private void toIoDeviceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toIoDeviceMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        IODeviceMenu ioDeviceMenu = new IODeviceMenu();
        ioDeviceMenu.setVisible(true);
    }//GEN-LAST:event_toIoDeviceMenuActionPerformed

    private void toProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toProfileButtonActionPerformed
        this.dispose();
        ProfileMenu profileMenu = new ProfileMenu();
        profileMenu.setVisible(true);
    }//GEN-LAST:event_toProfileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton logoutButton;
    private javax.swing.JLabel mainMenuLabel;
    private javax.swing.JToggleButton toComputerMenuButton;
    private javax.swing.JButton toIoDeviceMenu;
    private javax.swing.JButton toOrderMenuButton;
    private javax.swing.JToggleButton toProfileButton;
    private javax.swing.JButton toSoftwareSystemMenuButton;
    // End of variables declaration//GEN-END:variables
}
